sudo: false
language: node_js
node_js:
  - '5'

env:
  global:
    - CXX=g++-4.8

matrix:
  include:
  - env: SCRIPT=lint
  - env: SCRIPT=coveralls
  - env: SCRIPT=publish

cache:
  directories:
    - node_modules

script:
  - if [ "$SCRIPT" ]; then npm run $SCRIPT; fi
