sudo: false
language: node_js
node_js:
  - '5'

env:
  global:
    - CXX=g++-4.8

matrix:
  include:
  - env: SCRIPT=lint
  - env: SCRIPT=coveralls

cache:
  directories:
    - node_modules

script:
  - npm run $SCRIPT

after_script:
  - npm run publish
